#!/bin/bash

# downloads a local copy of qemu on docker-hub build machines
#curl -L https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-arm.tar.gz | tar zxvf - -C . && mv qemu-3.0.0+resin-arm/qemu-arm-static .
curl -L https://github.com/balena-io/qemu/releases/download/v6.0.0%2Bbalena1/qemu-6.0.0.balena1-arm.tar.gz | tar zxvf - -C . && mv qemu-6.0.0.balena1-arm/qemu-arm-static .
